@echo off
echo Creating .env files...

(
echo NODE_ENV=development
echo PORT=3001
echo FRONTEND_URL=http://localhost:5173,http://localhost:3002,http://localhost:3000
echo(
echo SUPABASE_URL=https://lcfuuwwsfqdhphhsbkky.supabase.co
echo SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjZnV1d3dzZnFkaHBoaHNia2t5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk2MzY4MDQsImV4cCI6MjA5NTIxMjgwNH0.6URlrFWA3stY0GDrS_RoGzBNH0-i6nhqopfMCib9Nu8
echo SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjZnV1d3dzZnFkaHBoaHNia2t5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3OTYzNjgwNCwiZXhwIjoyMDk1MjEyODA0fQ.FlumIjB9yMdLyuEy9diHVseerM_3CAWcC-X-ytX-I9k
echo SUPABASE_JWT_SECRET=t9zpNECJej8IMaoJMY4yIcSb8P9N4HQa9nKJ1nQGm5+JSl9u15mBPZb8sOs2kPoqb4ct7j/4dXapCuweVJDUOA==
echo(
echo ANTHROPIC_API_KEY=REMPLACER_PAR_ANTHROPIC_KEY
echo NOTCHPAY_SECRET_KEY=sk_test.ChKynWPtyiYa9oe5TMue9DwxKPtuiuxeoaC5gzW5EQPiLWQMtFvnEcutzYS9fXWR9ZqC6ypgTWhf1aJBsMuoqpQG3HuwdKKdwl1DAGQGPkcIIbRs7uabvEie3YbxS
echo CALLMEBOT_APIKEY=REMPLACER
echo JWT_SECRET=dev-local-secret-forge-tafdil-2026
) > "apps\api\.env"

(
echo VITE_API_URL=http://localhost:3001
echo VITE_SUPABASE_URL=https://lcfuuwwsfqdhphhsbkky.supabase.co
echo VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjZnV1d3dzZnFkaHBoaHNia2t5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk2MzY4MDQsImV4cCI6MjA5NTIxMjgwNH0.6URlrFWA3stY0GDrS_RoGzBNH0-i6nhqopfMCib9Nu8
echo VITE_SHOP_URL=https://forge-tafdil-erp-shop.vercel.app/
) > "apps\web\.env.local"

(
echo VITE_API_URL=http://localhost:3001
) > "apps\web\.env.development.local"

(
echo SUPABASE_URL=https://lcfuuwwsfqdhphhsbkky.supabase.co
echo SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjZnV1d3dzZnFkaHBoaHNia2t5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk2MzY4MDQsImV4cCI6MjA5NTIxMjgwNH0.6URlrFWA3stY0GDrS_RoGzBNH0-i6nhqopfMCib9Nu8
echo SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjZnV1d3dzZnFkaHBoaHNia2t5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3OTYzNjgwNCwiZXhwIjoyMDk1MjEyODA0fQ.FlumIjB9yMdLyuEy9diHVseerM_3CAWcC-X-ytX-I9k
echo SUPABASE_JWT_SECRET=t9zpNECJej8IMaoJMY4yIcSb8P9N4HQa9nKJ1nQGm5+JSl9u15mBPZb8sOs2kPoqb4ct7j/4dXapCuweVJDUOA==
) > "apps\desktop\.env"

(
echo NEXT_PUBLIC_API_URL=http://localhost:3002
echo NEXT_PUBLIC_SUPABASE_URL=https://lcfuuwwsfqdhphhsbkky.supabase.co
echo NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjZnV1d3dzZnFkaHBoaHNia2t5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk2MzY4MDQsImV4cCI6MjA5NTIxMjgwNH0.6URlrFWA3stY0GDrS_RoGzBNH0-i6nhqopfMCib9Nu8
echo SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjZnV1d3dzZnFkaHBoaHNia2t5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3OTYzNjgwNCwiZXhwIjoyMDk1MjEyODA0fQ.FlumIjB9yMdLyuEy9diHVseerM_3CAWcC-X-ytX-I9k
echo NEXT_PUBLIC_SITE_URL=http://localhost:3002
echo NEXT_PUBLIC_WHATSAPP_NUMBER=+237 95884528
echo NOTCHPAY_PUBLIC_KEY=pk_test.0hDXFeck0FUE28nnpbmoVJxGJuhMfZGO2eFpjuzhhY8DFJamGNfkjJBOBgSIW9eRrAZ31FoTm4vlwESIvjIS8wBUfPVk6YGAtAsZ0FiTctR0emS5UNtuKROxedwYE
echo NOTCHPAY_SECRET_KEY=sk_test.ChKynWPtyiYa9oe5TMue9DwxKPtuiuxeoaC5gzW5EQPiLWQMtFvnEcutzYS9fXWR9ZqC6ypgTWhf1aJBsMuoqpQG3HuwdKKdwl1DAGQGPkcIIbRs7uabvEie3YbxS
echo JWT_SECRET=dev-local-secret-forge-tafdil-2026
echo SMS_PROVIDER=
echo AT_API_KEY=atsk_66f0963f78a0f855f2b345cfc6fd1352d11d0d5241ea0d654933c1a63f23a7e69be1d3b8
echo AT_USERNAME=sandbox
echo AT_SENDER_ID=AFRICASTALKING
) > "apps\shop\.env.local"

echo.
echo [OK] Tous les fichiers .env ont ete crees avec succes !
pause
